name: Trigger auto deployment for conthello098

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/conthello098-AutoDeployTrigger-c56ab8a8-bf2d-439e-a1f3-607e6d37803e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTHELLO098_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTHELLO098_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTHELLO098_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acaregistry.azurecr.io
          registryUsername: ${{ secrets.CONTHELLO098_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTHELLO098_REGISTRY_PASSWORD }}
          containerAppName: conthello098
          resourceGroup: OGFS265-190526-gayathri
          imageToBuild: acaregistry.azurecr.io/conthello098:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


